version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
    - ./.env
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  web:
    image: pashvd/foodgram:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static:/code/static/
      - media:/code/media/

  nginx:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static:/code/static/
      - media:/code/media/
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
