# Generated by Django 3.2.4 on 2021-08-30 12:50

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(help_text='время в минутах', validators=[recipes.validators.validate_time], verbose_name='время приготовления'),
        ),
    ]
